In [ ]:
pip install numpy

In [ ]:
import numpy as np  

In [2]:
arr = np.array([1,2,3,4,5]) # 1. using list
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
arr = np.array((1, 2, 3, 4, 5)) # 2. using a tuple
print(arr)

[1 2 3 4 5]


In [4]:
arr = np.zeros((5,5,4)) # 3. using zeros function 
print (arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [5]:
arr = np.ones((2,2)) #4. using ones function
print(arr)

[[1. 1.]
 [1. 1.]]


In [6]:
arr = np.arange(1,10,2) #5. using arange 
print (arr) 
# difference between range and arange function

[1 3 5 7 9]


In [8]:
arr = np.arange(1,2,0.1)
print (arr) 

a = range(1,2, 0.1)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]


TypeError: 'float' object cannot be interpreted as an integer

In [10]:
arr= np.linspace(1,10,5) # 6. using linspace 
print (arr)
# difference between linespace and arange 

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
# copy an array
arr = np.ones((2,2))
c = np.copy(arr)
arr[0][0] = 0
print (arr)
print (c)

[[0. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2 dimensional array
#  to check the number of dimensions  

In [13]:
a = np.array(42) 
b = np.array([1, 2, 3, 4, 5.0])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
# to check the properties of the array
# 2. ndarray.shape
print(d.ndim)
print (d.shape)
print(d.size)
print(d.dtype)
print (d.itemsize)

3
(2, 2, 3)
12
int32
4


In [18]:
# to create an array of 5 dimens 
arr = np.array([1, 2, 3, 4], ndmin=5) # use ndmin
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [19]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr) 
print('shape of array :', arr.shape) # what will be the output?

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [20]:
# #reshaping an array: changing the shape of array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# convert into 3D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [25]:
#flattening the array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
newarr = arr.reshape(-1)
print(newarr)

(2, 3)
[1 2 3 4 5 6]
