## Understanding Array Functions

Q: Write a Python program that takes the speeds of any vehicle to store it in a NumPy

array and calculates the average speed.

In [2]:
import numpy as np
n = int(input("What number of speeds you want to enter?"))

speeds = []
for i in range(n):
    sp = int(input("Enter the speeds in Km/hr"))
    speeds.append(sp)

speedsNp = np.array(speeds)

print("The Average speed is:",speedsNp.mean(),"Km/hr")


What number of speeds you want to enter? 5
Enter the speeds in Km/hr 92
Enter the speeds in Km/hr 76
Enter the speeds in Km/hr 83
Enter the speeds in Km/hr 78
Enter the speeds in Km/hr 84


The Average speed is: 82.6 Km/hr


## Array Indexing/Slicing

Q: Write a Python program to generate a 3-D array with  integers of your choice, perform indexing, and

print the first two rows and last two columns of the array

<b>Note:</b> Use NumPy arange() function to generate a random array.

In [17]:
a = np.arange(20).reshape(5,4)

print("The array is:")
print(a)
print("The first two rows are:")
print(a[:2,:])
print("The last two columns are:")
print(a[:,2:])

The array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The first two rows are:
[[0 1 2 3]
 [4 5 6 7]]
The last two columns are:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
