## Understanding Array Manipulation - I

Q: Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to make

it 5*4 using suitable functions.

In [4]:
import numpy as np

arr = np.arange(20)

a = arr.reshape(4,5)

b = np.transpose(a)

print("Original Array:")
print(arr)

print("Reshaped Array:")
print(a)

print("Transpose of Array:")
print(b)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Transpose of Array:
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Q: Write a Python program to create two 2-dimensional arrays and apply hstack(), vstack(),

concatenate(), and split() functions to them to get the output as shown below.

