## Understanding Array Manipulation - I

Q: Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to make

it 5*4 using suitable functions.

In [6]:
import numpy as np

arr = np.arange(20)

a = arr.reshape(4,5)

b = np.transpose(a)

print("Original Array:")
print(arr)

print("Reshaped Array:")
print(a)

print("Transpose of Array:")
print(b)

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reshaped Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Transpose of Array:
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


## Understanding Array Manipulation - II

Q: Write a Python program to create two 2-dimensional arrays and apply hstack(), vstack(),

concatenate(), and split() functions to them to get the output.

In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[6,7],[8,9]])

print("First array is:")
print(x)

print("Second array is:")
print(y)

print("Applying hstack() function:")
hstack = np.hstack((x,y))
print(hstack)

print("Applying vstack() function:")
vstack = np.vstack((x,y))
print(vstack)

print("Applying concatenate() function:")
concatenate = np.concatenate((x,y),axis=0)
print(concatenate)

print("Applying split() function:")
hsplit = np.split(hstack,2)
print(hsplit)

First array is:
[[1 2]
 [3 4]]
Second array is:
[[6 7]
 [8 9]]
Applying hstack() function:
[[1 2 6 7]
 [3 4 8 9]]
Applying vstack() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying concatenate() function:
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
Applying split() function:
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
